# Generated by Django 3.1.3 on 2020-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201208_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('bangla', 'BANGLA')], max_length=10),
        ),
    ]
