# Generated by Django 3.1.3 on 2020-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailler',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
